const fs = require('fs');

const CATEGORIES = [
  { key: 'shawarma', name_en: 'Shawarma & Boxes', name_ar: 'شاورما وبوكسات', img: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800&auto=format&fit=crop', desc_en: 'Authentic Syrian shawarma wraps and rice boxes', desc_ar: 'شاورما سورية أصيلة وبوكسات بالأرز' },
  { key: 'sandwiches', name_en: 'Sandwiches & Western', name_ar: 'سندوتشات وغربي', img: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=800&auto=format&fit=crop', desc_en: 'Crispy burgers, chicken strips and western-style sandwiches', desc_ar: 'برجر كريسبي وستربس واستراحة غربي' },
  { key: 'crepe', name_en: 'Crepe', name_ar: 'كريب', img: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=800&auto=format&fit=crop', desc_en: 'Sweet and savoury thin French crêpes', desc_ar: 'كريب فرنسي حلو ومالح' },
  { key: 'pizza', name_en: 'Pizza & Manakish', name_ar: 'بيتزا ومناقيش', img: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&auto=format&fit=crop', desc_en: 'Stone-baked pizzas and authentic Syrian manakish', desc_ar: 'بيتزا محجر ومناقيش سورية أصيلة' },
  { key: 'meals', name_en: 'Meals & Trays', name_ar: 'وجبات وصواني', img: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=800&auto=format&fit=crop', desc_en: 'Full family meals, grills and Syrian-style rice trays', desc_ar: 'وجبات عائلية كاملة ومشاوي وصواني أرز' },
  { key: 'appetizers', name_en: 'Fatteh & Appetizers', name_ar: 'فتة ومقبلات', img: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&auto=format&fit=crop', desc_en: 'Levantine starters, dips and hot fattehs', desc_ar: 'مقبلات شامية وفتة ساخنة وتشكيلة شرقية' },
  { key: 'sauces', name_en: 'Sauces & Extras', name_ar: 'الصوصات والإضافات', img: 'https://images.unsplash.com/photo-1472476443507-c7a5948772bf?w=800&auto=format&fit=crop', desc_en: 'Delicious sauces and extra additions for your meal', desc_ar: 'تشكيلة صوصات شهية وإضافات جانبية للوجبات' },
  { key: 'drinks', name_en: 'Drinks & Bar', name_ar: 'مشروبات وبار', img: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=800&auto=format&fit=crop', desc_en: 'Fresh juices, hot beverages and signature cocktails', desc_ar: 'عصائر طازجة ومشروبات ساخنة وكوكتيل' },
];

const PRODUCTS = [
  { category_key: 'shawarma', key: 'sh_suri_chicken', name_en: 'Suri Chicken Shawarma', name_ar: 'شاورما سوري فراخ', desc_en: '', desc_ar: '', price: { 'L': 90, 'XL': 100 }, weight: '', img: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=600&auto=format&fit=crop', sauces: [{ name: 'تومية', price: 0, is_default: true }, { name: 'صوص حار', price: 10, is_default: false }, { name: 'مخلل إضافي', price: 5, is_default: false }], ingredients: ['دجاج سوري', 'خيار مخلل', 'خبز صاج'], is_popular: 1, offer_type: 'none' },
  { category_key: 'shawarma', key: 'sh_suri_meat', name_en: 'Suri Meat Shawarma', name_ar: 'شاورما سوري لحم بلدي', desc_en: '', desc_ar: '', price: 125, weight: '', img: 'https://images.unsplash.com/photo-1541014741259-de529411b96a?w=600&auto=format&fit=crop', sauces: [], ingredients: [], is_popular: 0, offer_type: 'none' },
  { category_key: 'shawarma', key: 'sh_suri_mix', name_en: 'Mix Meat/Chicken Shawarma', name_ar: 'شاورما ميكس لحم/فراخ', desc_en: '', desc_ar: '', price: 125, weight: '', img: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&auto=format&fit=crop', sauces: [], ingredients: [], is_popular: 1, offer_type: 'none' },
  { category_key: 'shawarma', key: 'box_arabi_chicken_single', name_en: 'Arabic Chicken Shawarma Box Single', name_ar: 'وجبة شاورما عربي فراخ سنجل', desc_en: '8 pieces of shawarma, fries, garlic sauce, pickles', desc_ar: '8 قطع شاورما، بطاطس، تومية، مخلل', price: 135, weight: '', img: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&auto=format&fit=crop', sauces: [], ingredients: ['8 قطع شاورما', 'بطاطس', 'تومية', 'مخلل'], is_popular: 1, offer_type: 'none' },
  { category_key: 'shawarma', key: 'box_arabi_meat_single', name_en: 'Arabic Meat Shawarma Box Single', name_ar: 'وجبة شاورما عربي لحمة سنجل', desc_en: '8 pieces of shawarma, fries, garlic sauce, pickles', desc_ar: '8 قطع شاورما، بطاطس، تومية، مخلل', price: 160, weight: '', img: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&auto=format&fit=crop', sauces: [{ name: 'طحينة', price: 0, is_default: true }, { name: 'دبس رمان', price: 15, is_default: false }, { name: 'صوص حار', price: 10, is_default: false }], ingredients: ['8 قطع شاورما', 'بطاطس', 'تومية', 'مخلل'], is_popular: 0, offer_type: 'none' },
  { category_key: 'shawarma', key: 'box_egyptian', name_en: 'Egyptian Shawarma Box', name_ar: 'بوكس شاورما مصري', desc_en: '2 meat, 2 chicken, fries', desc_ar: '2 لحمة، 2 فراخ، بطاطس', price: 200, weight: '', img: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&auto=format&fit=crop', sauces: [], ingredients: ['2 لحمة', '2 فراخ', 'بطاطس'], is_popular: 1, offer_type: 'none' },
  { category_key: 'crepe', key: 'cr_sh_chicken', name_en: 'Chicken Shawarma Crepe', name_ar: 'كريب شاورما فراخ', desc_en: '', desc_ar: '', price: 130, weight: '', img: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=600&auto=format&fit=crop', sauces: [], ingredients: [], is_popular: 1, offer_type: 'none' },
  { category_key: 'crepe', key: 'cr_sh_meat', name_en: 'Meat Shawarma Crepe', name_ar: 'كريب شاورما لحمة', desc_en: '', desc_ar: '', price: 160, weight: '', img: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=600&auto=format&fit=crop', sauces: [], ingredients: [], is_popular: 0, offer_type: 'none' },
  { category_key: 'crepe', key: 'cr_zinger', name_en: 'Zinger Crepe', name_ar: 'كريب زنجر', desc_en: '', desc_ar: '', price: 125, weight: '', img: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=600&auto=format&fit=crop', sauces: [], ingredients: [], is_popular: 1, offer_type: 'none' },
  { category_key: 'crepe', key: 'cr_mix_cheese', name_en: 'Mix Cheese Crepe', name_ar: 'كريب ميكس جبن', desc_en: '', desc_ar: '', price: 110, weight: '', img: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=600&auto=format&fit=crop', sauces: [], ingredients: [], is_popular: 0, offer_type: 'none' },
  { category_key: 'pizza', key: 'pz_margherita', name_en: 'Margherita Pizza', name_ar: 'مارجريتا', desc_en: '', desc_ar: '', price: { 'M': 130, 'L': 165 }, weight: '', img: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&auto=format&fit=crop', sauces: [{ name: 'كاتشب', price: 0, is_default: true }, { name: 'إكسترا جبنة', price: 30, is_default: false }, { name: 'صوص رانش', price: 15, is_default: false }], ingredients: [], is_popular: 1, offer_type: 'none' },
  { category_key: 'pizza', key: 'pz_sh_chicken', name_en: 'Chicken Shawarma Pizza', name_ar: 'بيتزا شاورما فراخ', desc_en: '', desc_ar: '', price: { 'M': 180, 'L': 215 }, weight: '', img: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&auto=format&fit=crop', sauces: [], ingredients: [], is_popular: 1, offer_type: 'none' },
  { category_key: 'pizza', key: 'pz_mix_meat', name_en: 'Mix Meat Pizza', name_ar: 'بيتزا مشكل لحوم', desc_en: '', desc_ar: '', price: { 'M': 175, 'L': 235 }, weight: '', img: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600&auto=format&fit=crop', sauces: [], ingredients: [], is_popular: 0, offer_type: 'none' },
  { category_key: 'meals', key: 'meal_broasted_4', name_en: 'Broasted 4 Pieces Meal', name_ar: 'وجبة بروست 4 قطعة', desc_en: 'Fries, garlic sauce, coleslaw, bun', desc_ar: 'بطاطس، تومية، كولوسلو، خبز كيزر', price: 245, weight: '', img: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=600&auto=format&fit=crop', sauces: [], ingredients: ['بطاطس', 'تومية', 'كولوسلو', 'خبز كيزر'], is_popular: 1, offer_type: 'none' },
  { category_key: 'meals', key: 'meal_zinger', name_en: 'Zinger Meal', name_ar: 'وجبة زنجر', desc_en: 'Rice, fries, garlic sauce, pickles, bread', desc_ar: 'أرز، بطاطس، تومية، مخلل، خبز', price: 220, weight: '', img: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=600&auto=format&fit=crop', sauces: [], ingredients: ['أرز', 'بطاطس', 'تومية', 'مخلل', 'خبز'], is_popular: 1, offer_type: 'none' },
  { category_key: 'appetizers', key: 'app_garlic', name_en: 'Normal Garlic Sauce', name_ar: 'تومية عادي', desc_en: '', desc_ar: '', price: 25, weight: '', img: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600&auto=format&fit=crop', sauces: [], ingredients: [], is_popular: 0, offer_type: 'none' },
  { category_key: 'appetizers', key: 'app_cheddar_fries', name_en: 'Cheddar Fries', name_ar: 'بطاطس شيدر', desc_en: '', desc_ar: '', price: 55, weight: '', img: 'https://images.unsplash.com/photo-1541518763669-27fef04b14e8?w=600&auto=format&fit=crop', sauces: [], ingredients: [], is_popular: 1, offer_type: 'none' },
  { category_key: 'appetizers', key: 'app_coleslaw', name_en: 'Coleslaw Salad', name_ar: 'سلطة كولوسلو', desc_en: '', desc_ar: '', price: 25, weight: '', img: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600&auto=format&fit=crop', sauces: [], ingredients: [], is_popular: 0, offer_type: 'none' },
  { category_key: 'sauces', key: 'sauce_garlic_syr', name_en: 'Authentic Syrian Garlic Sauce', name_ar: 'ثومية سوري أصلية', desc_en: 'Available in small and large sizes', desc_ar: 'متوفرة بحجم عادي وحجم كبير', price: JSON.stringify({ 'عادي': 15, 'كبير': 30 }), weight: '', img: 'https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=600&auto=format&fit=crop', sauces: [], ingredients: [], is_popular: 1, offer_type: 'none' },
  { category_key: 'sauces', key: 'sauce_garlic_spicy', name_en: 'Spicy Garlic Sauce', name_ar: 'ثومية حارة (سبيسي)', desc_en: 'Authentic garlic sauce with a spicy kick', desc_ar: 'ثومية أصلية بلمسة حارة مميزة', price: 15, weight: '', img: 'https://images.unsplash.com/photo-1564834724105-918b73d1b9e0?w=600&auto=format&fit=crop', sauces: [], ingredients: [], is_popular: 1, offer_type: 'none' },
  { category_key: 'sauces', key: 'sauce_tahini', name_en: 'Syrian Tahini', name_ar: 'طحينة سورية أصلية', desc_en: 'Rich sesame tahini sauce', desc_ar: 'صوص الطحينة الغني بالسمسم على الطريقة السورية', price: 15, weight: '', img: 'https://images.unsplash.com/photo-1596662951482-0c4ba74a6df6?w=600&auto=format&fit=crop', sauces: [], ingredients: [], is_popular: 0, offer_type: 'none' },
  { category_key: 'sauces', key: 'sauce_hot', name_en: 'Spicy Syrian Hot Sauce', name_ar: 'صوص حار / شطة سورية', desc_en: 'Fiery Syrian hot sauce', desc_ar: 'شطة سورية أصلية لعشاق الحار', price: 10, weight: '', img: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&auto=format&fit=crop', sauces: [], ingredients: [], is_popular: 0, offer_type: 'none' },
  { category_key: 'sauces', key: 'sauce_pickles', name_en: 'Mixed Pickles Plate', name_ar: 'طبق مخلل مشكل (خيار ولفت معتبر)', desc_en: 'Cucumber, turnip, and assorted pickles', desc_ar: 'تشكيلة من الخيار واللفت المخلل السوري', price: 15, weight: '', img: 'https://images.unsplash.com/photo-1604543519968-71e8476a6ce0?w=600&auto=format&fit=crop', sauces: [], ingredients: [], is_popular: 1, offer_type: 'none' },
  { category_key: 'sauces', key: 'sauce_cheddar', name_en: 'Warm Cheddar Sauce', name_ar: 'صوص شيدر دافئ', desc_en: 'Melted cheddar cheese dip', desc_ar: 'صوص الجبنة الشيدر الدافئ واللذيذ', price: 20, weight: '', img: 'https://images.unsplash.com/photo-1616409540073-455b79644365?w=600&auto=format&fit=crop', sauces: [], ingredients: [], is_popular: 1, offer_type: 'none' },
  { category_key: 'sauces', key: 'sauce_bbq', name_en: 'BBQ Sauce', name_ar: 'صوص باربكيو', desc_en: 'Smoky barbecue sauce', desc_ar: 'صوص الباربكيو المدخن', price: 10, weight: '', img: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&auto=format&fit=crop', sauces: [], ingredients: [], is_popular: 0, offer_type: 'none' }
];

let sql = `
DELETE FROM products;
DELETE FROM categories;
`;

CATEGORIES.forEach(c => {
  sql += `INSERT INTO categories (key, name_en, name_ar, img, desc_en, desc_ar) VALUES ('${c.key}', '${c.name_en}', '${c.name_ar}', '${c.img}', '${c.desc_en}', '${c.desc_ar}');\n`;
});

PRODUCTS.forEach(p => {
  const price = typeof p.price === 'string' ? p.price : JSON.stringify(p.price);
  sql += `INSERT INTO products (category_key, key, name_en, name_ar, desc_en, desc_ar, price, img, weight, sauces, ingredients, is_popular, offer_type) VALUES ('${p.category_key}', '${p.key}', '${p.name_en}', '${p.name_ar}', '${p.desc_en}', '${p.desc_ar}', '${price}', '${p.img}', '${p.weight}', '${JSON.stringify(p.sauces || [])}', '${JSON.stringify(p.ingredients || [])}', ${p.is_popular}, '${p.offer_type}');\n`;
});

fs.writeFileSync('backend/seed.sql', sql);
console.log('seed.sql generated!');
